spring:
  application:
    name: incidents-management
  
  datasource:
    url: jdbc:postgresql://localhost:5432/incidents_db
    username: ${POSTGRES_USER:incidents_user}
    password: ${POSTGRES_PASSWORD:incidents_pass}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  security:
    jwt:
      secret: ${JWT_SECRET:aW5jaWRlbnRzX2p3dF9zZWNyZXRfa2V5XzIwMjRfdmVyeV9sb25nX2FuZF9zZWN1cmVfYmFzZTY0}
      expiration: 86400000 # 24 horas

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    operations-sorter: method
    tags-sorter: alpha
  info:
    title: API de Gestão de Ocorrências
    description: Sistema completo para gestão de incidentes e ocorrências
    version: 1.0.0
    contact:
      name: Equipe de Desenvolvimento
      email: dev@incidents.com
